#!/usr/bin/env bash
# Apply the local patch layer to a vendor foodon.owl and produce a queryable graph.
#
#   ./tools/apply_patches.sh
#
# Takes ontology/foodon.owl exactly as shipped by FoodOn and never writes to it.
# To adopt a new upstream release: replace that one file, re-run this, and the
# patch layer re-applies unchanged. Everything this script writes is derived and
# safe to delete.
#
#   foodon.owl                  vendor, untouched
# + foodon-local-patches.ttl    generated by build/emit_patches.py
# = foodon-merged.owl           the two as one ontology (reasoners, ROBOT, upload)
# + foodon-avoidance.ttl        materialised one-hop avoidance relation
# = foodon-queryable.owl        what the SPARQL in build/sparql/ runs against
#
# The materialisation step exists because SPARQL 1.1 property paths cannot step
# through a blank-node owl:Restriction, so "subClassOf plus propagating properties"
# has no single-path form. Materialising the one hop lets a `+` path close it.
set -euo pipefail
cd "$(dirname "$0")/.."
ROBOT="java -Xmx10g -jar tools/robot.jar"
O=ontology

test -f $O/foodon.owl || { echo "missing $O/foodon.owl (the vendor file)"; exit 1; }
echo "vendor sha256: $(shasum -a 256 $O/foodon.owl | cut -c1-16)…"
test -f $O/foodon.owl.sha256 && \
  { grep -q "$(shasum -a 256 $O/foodon.owl | cut -d' ' -f1)" $O/foodon.owl.sha256 \
    && echo "  matches the pinned hash" \
    || echo "  WARNING: differs from $O/foodon.owl.sha256 -- new upstream release?"; }

echo "1/4  regenerating the patch layer from the governed decision files"
python3 build/emit_patches.py

echo "2/4  merging vendor + patches"
$ROBOT merge --input $O/foodon.owl --input $O/foodon-local-patches.ttl \
             --output $O/foodon-merged.owl

echo "3/4  materialising the one-hop avoidance relation"
$ROBOT query --input $O/foodon-merged.owl \
             --query build/sparql/patch_materialize_avoidance.rq $O/foodon-avoidance.ttl

echo "4/4  building the queryable graph"
$ROBOT merge --input $O/foodon-merged.owl --input $O/foodon-avoidance.ttl \
             --output $O/foodon-queryable.owl

echo
echo "validating: does paprika resolve as a Solanaceae product?"
$ROBOT query --input $O/foodon-merged.owl \
             --query build/sparql/patch_validate_paprika.rq /dev/stdout
echo
ls -la $O/*.owl $O/*.ttl | awk '{printf "  %-34s %10d\n", $NF, $5}'
